version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.0.0
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  frontend: # This is our first job
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/frontend
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run deploy:firebase
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  backend: # This is our second job
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Running NuGet"
          command: nuget restore $env:PATH_SOLUTION
      - run:
          name: "Building and publishing"
          command: msbuild $env:PATH_PROJECT /p:VisualStudioVersion=16.0 /p:DeployOnBuild=true /p:Configuration=Debug /p:PublishProfile=Properties/PublishProfiles/Production.pubxml /p:Password=$env:PRODUCTION_PASS
workflows:
  frontend_and_backend: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - frontend
      - backend:
          requires:
            - frontend