version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Running NuGet"
          command: nuget restore backend/UmbracoJAM.sln
      - run:
          name: "Building and publishing"
          command: msbuild backend/src/Project/UmbracoJAM/code/UmbracoJAM.Project.Web.csproj /p:VisualStudioVersion=16.0 /p:DeployOnBuild=true /p:Configuration=Debug /p:PublishProfile=Properties/PublishProfiles/Production.pubxml /p:Password=$env:PRODUCTION_PASS