version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.0.0
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  frontend: # This is our first job
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "./frontend/package.json" }}
            # Find the most recently generated cache used
            - v1-npm-deps-
      - run:
          working_directory: ~/repo/frontend
          command: npm install
      - run:
          working_directory: ~/repo/frontend
          command: npm run build
          
      - save_cache:
          key: v1-npm-deps-{{ checksum "./frontend/package.json" }}
          paths:
            - frontend/node_modules            
          
      - run:
          working_directory: ~/repo/frontend
          command: npm run deploy:firebase --token=$FIREBASE_TOKEN
  backend: # This is our second job
    executor:
      name: win/default
      shell: powershell.exe
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-nuget-deps-{{ checksum "./backend/src/Project/UmbracoJAM/code/packages.config" }}
            # Find the most recently generated cache used
            - v1-nuget-deps-
      - run:
          name: "Running NuGet"
          command: nuget restore $env:PATH_SOLUTION
      - save_cache:
          key: v1-nuget-deps-{{ checksum "./backend/src/Project/UmbracoJAM/code/packages.config" }}
          paths:
            - backend/packages
      - run:
          name: "Building and publishing"
          command: msbuild $env:PATH_PROJECT /p:VisualStudioVersion=16.0 /p:DeployOnBuild=true /p:PublishProfile=Properties/PublishProfiles/Production.pubxml /p:Password=$env:PRODUCTION_PASS
workflows:
  deploy: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - backend:
          filters:
            branches:
              only: master
      - frontend:
          requires:
            - backend
          filters:
            branches:
              only: master