version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor: win/vs2019
    steps:
      - checkout
      - working_directory: ~/backend/src/Project/UmbracoJAM/code
      - run: msbuild /t:Build