version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    filters:
      branches:
        only:
          - master
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          command: .circleci/publish-project.ps1